/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/sample-controller/pkg/apis/crdappcontroller/v1alpha1"
)

// FakeCrdapps implements CrdappInterface
type FakeCrdapps struct {
	Fake *FakeCrdappV1alpha1
	ns   string
}

var crdappsResource = schema.GroupVersionResource{Group: "crdapp.k8s.io", Version: "v1alpha1", Resource: "crdapps"}

var crdappsKind = schema.GroupVersionKind{Group: "crdapp.k8s.io", Version: "v1alpha1", Kind: "Crdapp"}

// Get takes name of the crdapp, and returns the corresponding crdapp object, and an error if there is any.
func (c *FakeCrdapps) Get(name string, options v1.GetOptions) (result *v1alpha1.Crdapp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(crdappsResource, c.ns, name), &v1alpha1.Crdapp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crdapp), err
}

// List takes label and field selectors, and returns the list of Crdapps that match those selectors.
func (c *FakeCrdapps) List(opts v1.ListOptions) (result *v1alpha1.CrdappList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(crdappsResource, crdappsKind, c.ns, opts), &v1alpha1.CrdappList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CrdappList{ListMeta: obj.(*v1alpha1.CrdappList).ListMeta}
	for _, item := range obj.(*v1alpha1.CrdappList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested crdapps.
func (c *FakeCrdapps) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(crdappsResource, c.ns, opts))

}

// Create takes the representation of a crdapp and creates it.  Returns the server's representation of the crdapp, and an error, if there is any.
func (c *FakeCrdapps) Create(crdapp *v1alpha1.Crdapp) (result *v1alpha1.Crdapp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(crdappsResource, c.ns, crdapp), &v1alpha1.Crdapp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crdapp), err
}

// Update takes the representation of a crdapp and updates it. Returns the server's representation of the crdapp, and an error, if there is any.
func (c *FakeCrdapps) Update(crdapp *v1alpha1.Crdapp) (result *v1alpha1.Crdapp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(crdappsResource, c.ns, crdapp), &v1alpha1.Crdapp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crdapp), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCrdapps) UpdateStatus(crdapp *v1alpha1.Crdapp) (*v1alpha1.Crdapp, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(crdappsResource, "status", c.ns, crdapp), &v1alpha1.Crdapp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crdapp), err
}

// Delete takes name of the crdapp and deletes it. Returns an error if one occurs.
func (c *FakeCrdapps) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(crdappsResource, c.ns, name), &v1alpha1.Crdapp{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCrdapps) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(crdappsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CrdappList{})
	return err
}

// Patch applies the patch and returns the patched crdapp.
func (c *FakeCrdapps) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Crdapp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(crdappsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Crdapp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crdapp), err
}
