/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "k8s.io/sample-controller/pkg/apis/crdappcontroller/v1alpha1"
	scheme "k8s.io/sample-controller/pkg/generated_crdapp/clientset/versioned/scheme"
)

// UnderlaysGetter has a method to return a UnderlayInterface.
// A group's client should implement this interface.
type UnderlaysGetter interface {
	Underlays(namespace string) UnderlayInterface
}

// UnderlayInterface has methods to work with Underlay resources.
type UnderlayInterface interface {
	Create(*v1alpha1.Underlay) (*v1alpha1.Underlay, error)
	Update(*v1alpha1.Underlay) (*v1alpha1.Underlay, error)
	UpdateStatus(*v1alpha1.Underlay) (*v1alpha1.Underlay, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Underlay, error)
	List(opts v1.ListOptions) (*v1alpha1.UnderlayList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Underlay, err error)
	UnderlayExpansion
}

// underlays implements UnderlayInterface
type underlays struct {
	client rest.Interface
	ns     string
}

// newUnderlays returns a Underlays
func newUnderlays(c *CrdappV1alpha1Client, namespace string) *underlays {
	return &underlays{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the underlay, and returns the corresponding underlay object, and an error if there is any.
func (c *underlays) Get(name string, options v1.GetOptions) (result *v1alpha1.Underlay, err error) {
	result = &v1alpha1.Underlay{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("underlays").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Underlays that match those selectors.
func (c *underlays) List(opts v1.ListOptions) (result *v1alpha1.UnderlayList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.UnderlayList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("underlays").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested underlays.
func (c *underlays) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("underlays").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a underlay and creates it.  Returns the server's representation of the underlay, and an error, if there is any.
func (c *underlays) Create(underlay *v1alpha1.Underlay) (result *v1alpha1.Underlay, err error) {
	result = &v1alpha1.Underlay{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("underlays").
		Body(underlay).
		Do().
		Into(result)
	return
}

// Update takes the representation of a underlay and updates it. Returns the server's representation of the underlay, and an error, if there is any.
func (c *underlays) Update(underlay *v1alpha1.Underlay) (result *v1alpha1.Underlay, err error) {
	result = &v1alpha1.Underlay{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("underlays").
		Name(underlay.Name).
		Body(underlay).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *underlays) UpdateStatus(underlay *v1alpha1.Underlay) (result *v1alpha1.Underlay, err error) {
	result = &v1alpha1.Underlay{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("underlays").
		Name(underlay.Name).
		SubResource("status").
		Body(underlay).
		Do().
		Into(result)
	return
}

// Delete takes name of the underlay and deletes it. Returns an error if one occurs.
func (c *underlays) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("underlays").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *underlays) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("underlays").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched underlay.
func (c *underlays) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Underlay, err error) {
	result = &v1alpha1.Underlay{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("underlays").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
